// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteMonitorAPI.Database;

namespace WasteMonitorAPI.Migrations
{
    [DbContext(typeof(WasteMonitorContext))]
    partial class WasteMonitorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WasteMonitorAPI.Database.WasteData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<double>("FillingLevel");

                    b.Property<double>("Weight");

                    b.Property<bool>("wasEmptied");

                    b.HasKey("Id");

                    b.ToTable("WasteData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2019, 6, 11, 17, 7, 41, 814, DateTimeKind.Local).AddTicks(8933),
                            FillingLevel = 0.5,
                            Weight = 20.0,
                            wasEmptied = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
